# Setup
title:               Yueting Chen
tagline:             'Homepage'
description:         'Yueting Chen Personal Website'
url:                 https://ytchen.me
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yueting Chen
  url:               https://ytchen.me
  email:             ychen24 [at] seattleu [dot] edu

# Gems
plugins:
  - jekyll-paginate
  - jekyll-scholar

scholar:
  style: apa
  locale: en
  sort_by: year,month
  order: descending
  source: _data
  bibliography: publications.bib
  bibliography_template: bibliography

# Custom vars
google_analytics_id: #UA-XXXX-Y
